// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 BorderKeys contributors

package com.borderkeys.theme

import android.content.Context
import android.os.Build
import androidx.core.content.ContextCompat
import com.borderkeys.data.theme.KeyboardTheme

/**
 * The keyboard's own theme, recoloured from the phone's wallpaper.
 *
 * There is no Compose here to hand a `dynamicLightColorScheme()`/`dynamicDarkColorScheme()` to --
 * the keyboard draws its own `Paint` objects from [KeyboardTheme], and `verifyKeyboardHasNoCompose`
 * means it always will. What Compose builds those two functions from is not hidden behind them,
 * though: `android.R.color.system_accent1_*`/`system_neutral1_*`/`system_neutral2_*` are plain
 * colour resources, generated by the system the moment the wallpaper changes, readable with
 * nothing more than [ContextCompat.getColor]. This reads the same tonal palette by hand and maps
 * it onto the same fields a preset would set.
 *
 * Introduced in Android 12 (API 31); [apply] is a no-op below that, since the resources this
 * reads do not exist there to be read.
 */
object DynamicColors {

    val available: Boolean
        get() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.S

    /**
     * [theme] with its palette replaced by the system's tonal one, or [theme] unchanged when
     * dynamic colour is unavailable or the resources cannot be read for some reason a running
     * phone can still hit -- a very early boot, a wallpaper mid-change. Never partial: either
     * every colour below came from the system, or none did, so a theme that half-updated
     * because one lookup failed never reaches the draw path.
     *
     * Shape and sizing -- corner radius, gaps, row height, patterns, the background picture --
     * are untouched. Those are the user's own choices about the keyboard's shape, not its
     * colour, and dynamic colour replaces only what a wallpaper actually has an opinion about.
     */
    fun apply(theme: KeyboardTheme, context: Context): KeyboardTheme {
        if (!available) {
            return theme
        }
        val stops = if (SystemDarkMode.isDark(context)) DARK_STOPS else LIGHT_STOPS
        val background = colorOf(context, stops.background) ?: return theme
        val key = colorOf(context, stops.key) ?: return theme
        val keyPressed = colorOf(context, stops.keyPressed) ?: return theme
        val modifierKey = colorOf(context, stops.modifierKey) ?: return theme
        val text = colorOf(context, stops.text) ?: return theme
        val secondaryText = colorOf(context, stops.secondaryText) ?: return theme
        val accent = colorOf(context, stops.accent) ?: return theme
        return theme.copy(
            backgroundColor = background,
            keyColor = key,
            keyPressedColor = keyPressed,
            modifierKeyColor = modifierKey,
            textColor = text,
            secondaryTextColor = secondaryText,
            accentColor = accent,
            // Keeps whatever transparency the theme's own trail already had -- a dynamic accent
            // hue, the same alpha, rather than a second opinion about how see-through it is.
            swipeTrailColor = (accent and 0x00FFFFFF) or (theme.swipeTrailColor and 0xFF000000.toInt()),
        )
    }

    private fun colorOf(context: Context, resId: Int): Int? =
        runCatching { ContextCompat.getColor(context, resId) }.getOrNull()

    /** Which tonal stop fills which role, one set per UI mode. */
    private class Stops(
        val background: Int,
        val key: Int,
        val keyPressed: Int,
        val modifierKey: Int,
        val text: Int,
        val secondaryText: Int,
        val accent: Int,
    )

    // Dark first, matching KeyboardTheme's own stated bias: a keyboard sits next to whatever
    // the user is reading, and a slab of white at the bottom of a dark app is what people
    // complain about first.
    private val DARK_STOPS = Stops(
        background = android.R.color.system_neutral1_900,
        key = android.R.color.system_neutral2_700,
        keyPressed = android.R.color.system_neutral2_600,
        modifierKey = android.R.color.system_neutral1_800,
        text = android.R.color.system_neutral1_50,
        secondaryText = android.R.color.system_neutral2_300,
        accent = android.R.color.system_accent1_200,
    )

    private val LIGHT_STOPS = Stops(
        background = android.R.color.system_neutral1_50,
        key = android.R.color.system_neutral1_100,
        keyPressed = android.R.color.system_neutral1_200,
        modifierKey = android.R.color.system_neutral2_50,
        text = android.R.color.system_neutral1_900,
        secondaryText = android.R.color.system_neutral2_600,
        accent = android.R.color.system_accent1_600,
    )
}
