// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 BorderKeys contributors

package com.borderkeys.ime

import android.content.res.AssetManager

/**
 * The apostrophe a word was written without, put back when the word is committed.
 *
 * Nobody reaches for the apostrophe in "don't" on a phone, and the search cannot recover it.
 * Continuing a prefix costs nothing while an edit costs forty times its distance, so "cant"
 * finds "cantor", "canterbury" and "canton" and never "can't", and no tuning of those constants
 * changes it without breaking correction everywhere else. Pricing the apostrophe cheaply fixed
 * the words that are prefixes of nothing -- "dont", "thats", "isnt" -- and could not touch the
 * rest. This is the answer for the rest: a plain mapping, consulted when the word ends, that
 * never enters the search at all.
 *
 * One list per bundled language in `assets/contractions/<tag>.txt`, generated by
 * `tools/make_contractions.py` from the same word counts the dictionaries are built from. A
 * mapping is written only where the apostrophe spelling outnumbers the bare one several times
 * over, which is what keeps "its", "were", "well" and "ill" out: in each of those the bare word
 * is the commoner one and nothing should rewrite it.
 *
 * **Every entry carries the languages that would disagree.** A bare spelling can be an ordinary
 * word elsewhere, so each line lists the other bundled languages whose own vocabulary holds it,
 * and [of] drops those entries when one of them is switched on. Somebody writing a single
 * language is never affected by any of them; somebody with English and French both on keeps
 * only the mappings neither language objects to.
 *
 * Every failure is empty, never an exception: a missing or malformed list means this language
 * restores no apostrophes, not a keyboard that will not start.
 */
object Contractions {

    private const val DIRECTORY = "contractions"

    /** What a committed word should be written as, or null to leave it alone. */
    fun expansionFor(typed: String, table: Map<String, String>): String? {
        if (typed.isEmpty() || table.isEmpty()) {
            return null
        }
        val written = table[typed] ?: table[typed.lowercase()] ?: return null
        // The list is lower case; a capital the user typed is theirs to keep.
        return if (typed[0].isUpperCase()) {
            written.replaceFirstChar { it.uppercaseChar() }
        } else {
            written
        }
    }

    /** One language's list, still carrying each entry's objectors. */
    fun load(assets: AssetManager, tag: String): List<Entry> = runCatching {
        assets.open("$DIRECTORY/$tag.txt").use { parse(it.readBytes().decodeToString()) }
    }.getOrElse { emptyList() }

    /** `typed<TAB>written<TAB>tag,tag`. Pure, so the format is tested on the JVM. */
    fun parse(text: String): List<Entry> {
        val entries = ArrayList<Entry>()
        for (line in text.lineSequence()) {
            if (line.isEmpty() || line.startsWith("#")) {
                continue
            }
            val fields = line.split('\t')
            if (fields.size < 2 || fields[0].isEmpty() || fields[1].isEmpty()) {
                continue
            }
            val objectors = if (fields.size < 3 || fields[2].isEmpty()) {
                emptyList()
            } else {
                fields[2].split(',').filter { it.isNotEmpty() }
            }
            entries.add(Entry(fields[0], fields[1], objectors))
        }
        return entries
    }

    /**
     * The table for the languages actually switched on.
     *
     * [enabled] is every active tag, this language's included. An entry goes in only when none
     * of the languages that claim its typed spelling is among them -- so "lets" restores an
     * apostrophe for someone writing English alone, and quietly stops doing so the moment they
     * turn on a language in which "lets" is an ordinary word.
     */
    fun of(perLanguage: List<List<Entry>>, enabled: Collection<String>): Map<String, String> {
        val table = HashMap<String, String>()
        for (entries in perLanguage) {
            for (entry in entries) {
                if (entry.objectors.any { it in enabled }) {
                    continue
                }
                table[entry.typed] = entry.written
            }
        }
        return table
    }

    /** One line: what was typed, what it should read, and who would object. */
    data class Entry(val typed: String, val written: String, val objectors: List<String>)
}
