#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Regenerates Keys.kt from the English catalogue.

Run after adding a string. CatalogueTest fails the build if the file is stale.
"""

import json
import pathlib

CATALOGUE = pathlib.Path("i18n/src/main/assets/translations/en.json")
OUT = pathlib.Path("i18n/src/main/java/com/borderkeys/i18n/Keys.kt")

HEADER = """// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 BorderKeys contributors

package com.borderkeys.i18n

/**
 * Every key in the translation catalogue, as a constant.
 *
 * Generated by tools/gen_keys.py from `assets/translations/en.json` and checked by
 * CatalogueTest.
 */
object Keys {
"""


def main():
    keys = sorted(json.loads(CATALOGUE.read_text(encoding="utf-8")))
    body = "".join(f'    const val {k.upper().replace("-", "_")} = "{k}"\n' for k in keys)
    OUT.write_text(HEADER + body + "}\n", encoding="utf-8")
    print(f"{len(keys)} keys -> {OUT}")


if __name__ == "__main__":
    main()
