#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Regenerates SettingsIndex.kt, the list of every titled row and card on every settings screen.

Reads the screen sources: a `SettingRow` or `SwitchRow` whose title is a catalogue key is one
entry, placed under the last `SettingsSectionCard` whose title is a catalogue key. A row or a
card titled from data (a learned word, a clip, a model name) is not indexed; nothing fixed can
be said about it. Run after adding or moving a row. SettingsIndexTest fails the build if the
file is stale.
"""

import pathlib
import re

SCREENS = pathlib.Path("settings/src/main/java/com/borderkeys/settings/screen")
OUT = pathlib.Path("settings/src/main/java/com/borderkeys/settings/SettingsIndex.kt")

# Sources that hold rows of a screen without being named after it.
EXTRA_SOURCES = {"EventEffectsSection.kt": "Effects"}

# Sources named like a screen that are not reached from Home: no entry in the Screen enum
# (opened by an intent), rows that only open other screens, or no fixed row at all.
SKIPPED_SCREENS = {"Home", "Features", "ProcessText", "Transfer"}

TITLE = r"\(\s*(?:title\s*=\s*)?strings(?:\[|\.getString\()Keys\.([A-Z0-9_]+)"
CARD = re.compile(r"SettingsSectionCard" + TITLE)
ANY_CARD = re.compile(r"SettingsSectionCard\(")
ROW = re.compile(r"(?:SettingRow|SwitchRow)" + TITLE)

HEADER = """// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 BorderKeys contributors

package com.borderkeys.settings

import com.borderkeys.i18n.Keys

/**
 * Every row and card on the settings screens whose title is a catalogue key, with the screen
 * it is on and the card it is under, in source order.
 *
 * Generated by tools/gen_settings_index.py from the screen sources and checked by
 * SettingsIndexTest, so a row added to a screen and left out of here fails the build rather
 * than going unfindable.
 */
object SettingsIndex {

    /** One indexed row or card: where it is and the key its title is drawn from. */
    class Entry(val screen: Screen, val cardKey: String?, val key: String)

    val entries: List<Entry> = listOf(
"""


def without_comments(text: str) -> str:
    """The source with comment-only lines blanked, so a call quoted in a comment is not a row."""
    lines = []
    for line in text.split("\n"):
        stripped = line.strip()
        lines.append("" if stripped.startswith("//") or stripped.startswith("*") else line)
    return "\n".join(lines)


def screen_of(name: str):
    if name in EXTRA_SOURCES:
        return EXTRA_SOURCES[name]
    if not name.endswith("Screen.kt"):
        return None
    screen = name[: -len("Screen.kt")]
    return None if screen in SKIPPED_SCREENS else screen


def scan(text: str, screen: str):
    """Yields (screen, card key, key) for every card and row in source order, each key once."""
    seen = set()
    card = None
    events = [(m.start(), "card", m) for m in ANY_CARD.finditer(text)]
    events += [(m.start(), "row", m) for m in ROW.finditer(text)]
    for position, kind, match in sorted(events, key=lambda e: e[0]):
        if kind == "card":
            titled = CARD.match(text, position)
            card = titled.group(1) if titled else None
            if card and (screen, card) not in seen:
                seen.add((screen, card))
                yield screen, None, card
        else:
            key = match.group(1)
            if (screen, key) not in seen:
                seen.add((screen, key))
                yield screen, card, key


def entries():
    known = set(re.findall(r"^\s+(\w+)\(Keys\.", pathlib.Path(
        "settings/src/main/java/com/borderkeys/settings/Screen.kt").read_text(), re.M))
    for path in sorted(SCREENS.glob("*.kt"), key=lambda p: p.name):
        screen = screen_of(path.name)
        if screen is None:
            continue
        if screen not in known:
            raise SystemExit(f"{path.name}: no Screen.{screen}")
        yield from scan(without_comments(path.read_text(encoding="utf-8")), screen)


def main():
    rows = list(entries())
    body = "".join(
        f"        Entry(Screen.{screen}, {'Keys.' + card if card else 'null'}, Keys.{key}),\n"
        for screen, card, key in rows
    )
    OUT.write_text(HEADER + body + "    )\n}\n", encoding="utf-8")
    print(f"{len(rows)} entries -> {OUT}")


if __name__ == "__main__":
    main()
