#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors

"""Derives each language's apostrophe-dropped spellings from its own word counts.

Nobody types the apostrophe in "don't" on a phone if they can avoid it, and the search cannot
recover it: continuing a prefix costs nothing while any edit costs forty times its distance, so
"cant" reaches "cantor", "canterbury" and "canton" and never "can't". Raising the apostrophe's
price fixed the words that are not prefixes of anything -- "dont", "thats", "isnt" -- and can do
nothing for the ones that are. This file is the answer for those: a plain mapping, applied when
the word is committed, that does not go through the search at all.

Which pairs are safe is decided from the counts rather than by hand
--------------------------------------------------------------------
For every word holding an apostrophe, drop it and ask what the bare spelling is worth. Three
things have to hold before a mapping is written:

  * the apostrophe spelling is used at all             (--min-count, default 50)
  * it beats the bare spelling by a wide margin        (--ratio, default 3)
  * the bare spelling is not a name                    (name rows are skipped)

The margin is what keeps the dangerous pairs out, and it separates them cleanly. "cant" against
"can't" is 108 to 3,713, a factor of 34, and "didnt" against "didn't" is 113 -- while "id"
against "I'd" is 1.07 and "wed" against "we'd" is 2.0, and both of those stay out on purpose:
"wed" is an ordinary verb and nobody should have it rewritten. "its", "were", "well" and "ill"
never come close, because in each the bare word is the commoner one by far.

Collisions with the other bundled languages
-------------------------------------------
A bare spelling can be an ordinary word somewhere else -- and then rewriting it is wrong for
anyone writing that language. Each entry therefore carries the tags of the other bundled
languages whose own vocabulary holds it, and the keyboard drops the entry when one of those is
switched on. Someone with a single language enabled is never affected by any of them.

Usage
-----
  tools/make_contractions.py            # report, write nothing
  tools/make_contractions.py --apply
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

BUNDLED = {
    "en_US": "en-US",
    "ro_RO": "ro-RO",
    "de_DE": "de-DE",
    "es_ES": "es-ES",
    "fr_FR": "fr-FR",
    "it_IT": "it-IT",
}

# A curly apostrophe means the same word; the keyboard emits the straight one, so that is what a
# replacement has to insert.
APOSTROPHES = ("'", "’")

HEADER = """\
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
#
# Apostrophe spellings restored when the bare one is committed. Generated by
# tools/make_contractions.py from this language's own word counts -- do not edit by hand.
#
# typed<TAB>written<TAB>other languages whose own vocabulary holds the typed spelling
"""


def read_list(path: Path) -> tuple[dict[str, int], set[str]]:
    """The word counts, and which rows are names."""
    counts: dict[str, int] = {}
    names: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        try:
            counts[parts[0]] = int(parts[1])
        except ValueError:
            continue
        if len(parts) >= 3 and parts[2] == "name":
            names.add(parts[0])
    return counts, names


def bare(word: str) -> str:
    for mark in APOSTROPHES:
        word = word.replace(mark, "")
    return word


def straight(word: str) -> str:
    return word.replace("’", "'")


def zipf_table(counts: dict[str, int]) -> dict[str, float]:
    total = sum(counts.values()) or 1
    scale = 1e9 / total
    return {word: math.log10(count * scale) for word, count in counts.items()}


def mappings(
    counts: dict[str, int], names: set[str], min_count: int, ratio: float,
    mine: dict[str, float] | None = None,
    others: list[dict[str, float]] | None = None,
    margin: float = 1.0,
) -> dict[str, tuple[str, int, int]]:
    """Bare spelling to the apostrophe spelling it should become, with both counts.

    [others] are the remaining bundled languages' frequency tables. An apostrophe word some
    other language knows an order of magnitude better is that language's, not this one's, and
    writing a mapping for it would hand a Romanian writer "dont" -> "don't" because Romanian web
    text quotes English. Same test drop_foreign.py applies to the vocabulary, for the same
    reason and against the same margin.
    """
    best: dict[str, tuple[str, int, int]] = {}
    for word, count in counts.items():
        if word in names or not any(mark in word for mark in APOSTROPHES):
            continue
        if mine is not None and others:
            own = mine.get(word)
            if own is not None and any(
                (table.get(word) or -99.0) > own + margin for table in others
            ):
                continue
        key = bare(word)
        if not key or key == word or not key.isalpha():
            continue
        if count < min_count:
            continue
        rival = counts.get(key, 0)
        if rival in names:
            continue
        if rival * ratio >= count:
            continue
        # The same bare spelling can come from two apostrophe words ("shes" from "she's" and
        # "shes'"); the commoner one wins, and the other is simply not offered.
        previous = best.get(key)
        if previous is None or count > previous[1]:
            best[key] = (straight(word), count, rival)
    return best


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dictionaries", type=Path, default=Path("dictionaries"))
    parser.add_argument("--out", type=Path,
                        default=Path("keyboard/src/main/assets/contractions"))
    parser.add_argument("--min-count", type=int, default=50)
    parser.add_argument("--ratio", type=float, default=3.0)
    parser.add_argument("--sample", type=int, default=10)
    parser.add_argument("--apply", action="store_true")
    arguments = parser.parse_args()

    available = [t for t in BUNDLED if (arguments.dictionaries / f"{t}.tsv").is_file()]
    if not available:
        print(f"no word lists in {arguments.dictionaries}", file=sys.stderr)
        return 1

    counts: dict[str, dict[str, int]] = {}
    names: dict[str, set[str]] = {}
    for tag in available:
        counts[tag], names[tag] = read_list(arguments.dictionaries / f"{tag}.tsv")

    zipf = {tag: zipf_table(counts[tag]) for tag in available}
    for tag in available:
        table = mappings(
            counts[tag], names[tag], arguments.min_count, arguments.ratio,
            mine=zipf[tag], others=[zipf[o] for o in available if o != tag],
        )
        lines = []
        clashing = 0
        for key in sorted(table):
            written, count, rival = table[key]
            others = sorted(
                BUNDLED[other] for other in available
                if other != tag and key in counts[other] and key not in names[other]
            )
            if others:
                clashing += 1
            lines.append(f"{key}\t{written}\t{','.join(others)}")
        print(f"{BUNDLED[tag]}: {len(table):,} mappings, {clashing:,} of them claimed by "
              f"another bundled language")
        for key in sorted(table, key=lambda k: -table[k][1])[:arguments.sample]:
            written, count, rival = table[key]
            print(f"    {key:<12} -> {written:<14} {count:>7,} against {rival:>6,}")
        if arguments.apply:
            arguments.out.mkdir(parents=True, exist_ok=True)
            path = arguments.out / f"{BUNDLED[tag]}.txt"
            path.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8")
            print(f"    written: {path}")
        print()

    if not arguments.apply:
        print("nothing written -- pass --apply")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
