#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of correctly spelled pack words across the frequency range, to be left alone.

Fifty words from each of four frequency bands, none a name. Every line is `word<TAB>word`, the
corpus idiom for "leave it alone", read by `suggest_eval --autocorrect`.

    python3 tools/make_known_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import sys

import corpus_words

SEED = 20261002
PER_BAND = 50
MIN_LENGTH = 3
BANDS = ((0, 2000), (2000, 10000), (10000, 40000), (40000, None))


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--per-band", type=int, default=PER_BAND)
    args = parser.parse_args()

    words = corpus_words.load(args.dictionary)
    rng = random.Random(SEED)
    bands = []
    for start, end in BANDS:
        eligible = [
            word for word, name in words.rows[start:end]
            if not name and word.isalpha() and word.islower() and len(word) >= MIN_LENGTH
        ]
        if not eligible:
            sys.exit(f"no eligible words in band {start}-{end}")
        bands.append((start, end, sorted(rng.sample(eligible, min(args.per_band, len(eligible))))))

    total = sum(len(rows) for _start, _end, rows in bands)
    print("# Correctly spelled pack words to be left alone, from four frequency bands, none a")
    print("# name. Generated by tools/make_known_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# {total} cases, {args.per_band} from each band.")
    for start, end, rows in bands:
        print(f"# ranks {start + 1} to {end if end is not None else 'the end'}")
        for word in rows:
            print(f"{word}\t{word}")


if __name__ == "__main__":
    main()
