#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors

"""Derives each language's apostrophe-dropped spellings from its own word counts.

A plain mapping, applied when the word is committed, outside the search. A mapping is written for
a word holding an apostrophe when:

  * the apostrophe spelling is used at all             (--min-count, default 50)
  * it beats the bare spelling by a wide margin        (--ratio, default 3)
  * the bare spelling is not a name                    (name rows are skipped)

Each entry carries the tags of the other bundled languages whose own vocabulary holds the bare
spelling; the keyboard drops the entry while one of those is switched on.

Beside each table, `<tag>.pairs.txt` lists the apostrophe spellings whose bare spelling is an
ordinary word of the list and not one the table rewrites, used at least --min-count times, with
both counts; a swipe offers the apostrophe spelling beside the bare one.

With --prune-bare TAG=HUNSPELL, the bare spellings the table rewrites that TAG's own word list
holds as ordinary words, and that the Hunspell dictionary at HUNSPELL rejects in every case form,
are dropped from the list (with --apply) or reported.

Usage
-----
  tools/make_contractions.py            # report, write nothing
  tools/make_contractions.py --apply
  tools/make_contractions.py --apply --prune-bare en_US=/path/to/en_US
"""

from __future__ import annotations

import argparse
import importlib.util
import math
import sys
from pathlib import Path

BUNDLED = {
    "en_US": "en-US",
    "ro_RO": "ro-RO",
    "de_DE": "de-DE",
    "es_ES": "es-ES",
    "fr_FR": "fr-FR",
    "it_IT": "it-IT",
}

# A curly apostrophe means the same word; the keyboard emits the straight one, so that is what a
# replacement has to insert.
APOSTROPHES = ("'", "’")

HEADER = """\
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
#
# Apostrophe spellings restored when the bare one is committed. Generated by
# tools/make_contractions.py from this language's own word counts -- do not edit by hand.
#
# typed<TAB>written<TAB>other languages whose own vocabulary holds the typed spelling
"""


PAIRS_HEADER = """\
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
#
# Apostrophe spellings offered beside a swiped bare spelling that is itself a word. Generated by
# tools/make_contractions.py from this language's own word counts -- do not edit by hand.
#
# bare<TAB>apostrophe spelling<TAB>bare count<TAB>apostrophe count
"""


def read_list(path: Path) -> tuple[dict[str, int], set[str]]:
    """The word counts, and which rows are names."""
    counts: dict[str, int] = {}
    names: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        try:
            counts[parts[0]] = int(parts[1])
        except ValueError:
            continue
        if len(parts) >= 3 and parts[2] == "name":
            names.add(parts[0])
    return counts, names


def bare(word: str) -> str:
    for mark in APOSTROPHES:
        word = word.replace(mark, "")
    return word


def straight(word: str) -> str:
    return word.replace("’", "'")


def zipf_table(counts: dict[str, int]) -> dict[str, float]:
    total = sum(counts.values()) or 1
    scale = 1e9 / total
    return {word: math.log10(count * scale) for word, count in counts.items()}


def mappings(
    counts: dict[str, int], names: set[str], min_count: int, ratio: float,
    mine: dict[str, float] | None = None,
    others: list[dict[str, float]] | None = None,
    margin: float = 1.0,
) -> dict[str, tuple[str, int, int]]:
    """Bare spelling to the apostrophe spelling it should become, with both counts.

    [others] are the remaining bundled languages' frequency tables. An apostrophe word another
    language knows an order of magnitude better is skipped, the test and margin drop_foreign.py
    applies to the vocabulary.
    """
    best: dict[str, tuple[str, int, int]] = {}
    for word, count in counts.items():
        if word in names or not any(mark in word for mark in APOSTROPHES):
            continue
        if mine is not None and others:
            own = mine.get(word)
            if own is not None and any(
                (table.get(word) or -99.0) > own + margin for table in others
            ):
                continue
        key = bare(word)
        if not key or key == word or not key.isalpha():
            continue
        if count < min_count:
            continue
        rival = counts.get(key, 0)
        if rival in names:
            continue
        if rival * ratio >= count:
            continue
        # The same bare spelling can come from two apostrophe words ("shes" from "she's" and
        # "shes'"); the commoner one wins, and the other is simply not offered.
        previous = best.get(key)
        if previous is None or count > previous[1]:
            best[key] = (straight(word), count, rival)
    return best


def pairs(
    counts: dict[str, int], names: set[str], min_count: int,
    mine: dict[str, float] | None = None,
    others: list[dict[str, float]] | None = None,
    margin: float = 1.0,
) -> dict[str, tuple[str, int, int]]:
    """Bare spelling to the apostrophe spelling beside it, with both counts, where the bare
    spelling is an ordinary word of the list: the apostrophe spelling used at least [min_count]
    times, neither a name, the commoner apostrophe spelling for each bare one; a bare spelling
    under three letters only beside a first-person form other than "i's". [others] skip an
    apostrophe word another language knows better, as [mappings] does."""
    best: dict[str, tuple[str, int, int]] = {}
    for word, count in counts.items():
        if word in names or not any(mark in word for mark in APOSTROPHES) or count < min_count:
            continue
        if mine is not None and others:
            own = mine.get(word)
            if own is not None and any(
                (table.get(word) or -99.0) > own + margin for table in others
            ):
                continue
        key = bare(word)
        if not key or key == word or not key.isalpha() or key in names:
            continue
        marked = straight(word)
        if len(key) < 3 and not (marked.lower().startswith("i'") and marked.lower() != "i's"):
            continue
        rival = counts.get(key, 0)
        if rival <= 0:
            continue
        previous = best.get(key)
        if previous is None or count > previous[2]:
            best[key] = (marked, rival, count)
    return best


def frequency_byte(count: int, top: int, total: int) -> int:
    """A count on a 0-255 scale, 255 for the commonest word: 255 * ln(p * 1e8 + 1) / ln(p_max *
    1e8 + 1), p the count's share of [total] and p_max [top]'s."""
    if count <= 0 or top <= 0 or total <= 0:
        return 0
    return int(255 * math.log(count / total * 1e8 + 1) / math.log(top / total * 1e8 + 1))


# Words a language always writes with a capital, whatever the corpus did, named per language
# as the single-letter words in drop_unreachable.py are. Value: the languages for which the same
# spelling is an ordinary word (Italian writes "i" as its plural article); Contractions.of drops
# an entry while one of them is also on.
ALWAYS_CAPITAL = {
    "en_US": {"i": ["it-IT"]},
}


def cased(written: str, tag: str) -> str:
    """[written] with any always-capital word of [tag] restored to its capital."""
    always = ALWAYS_CAPITAL.get(tag, {})
    if not always:
        return written
    head = written.split("'", 1)[0]
    if head in always:
        return written[:1].upper() + written[1:]
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dictionaries", type=Path, default=Path("dictionaries"))
    parser.add_argument("--out", type=Path,
                        default=Path("keyboard/src/main/assets/contractions"))
    parser.add_argument("--min-count", type=int, default=50)
    parser.add_argument("--ratio", type=float, default=3.0)
    parser.add_argument("--sample", type=int, default=10)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--prune-bare", action="append", default=[], metavar="TAG[=HUNSPELL]",
                        help="also drop from TAG's word list the bare spellings the table "
                             "rewrites, names aside; with =HUNSPELL only those the dictionary "
                             "at HUNSPELL rejects in every case form; TAG as in the file name")
    arguments = parser.parse_args()

    available = [t for t in BUNDLED if (arguments.dictionaries / f"{t}.tsv").is_file()]
    if not available:
        print(f"no word lists in {arguments.dictionaries}", file=sys.stderr)
        return 1

    counts: dict[str, dict[str, int]] = {}
    names: dict[str, set[str]] = {}
    for tag in available:
        counts[tag], names[tag] = read_list(arguments.dictionaries / f"{tag}.tsv")

    zipf = {tag: zipf_table(counts[tag]) for tag in available}
    for tag in available:
        table = mappings(
            counts[tag], names[tag], arguments.min_count, arguments.ratio,
            mine=zipf[tag], others=[zipf[o] for o in available if o != tag],
        )
        lines = []
        clashing = 0
        for key in sorted(table):
            written, count, rival = table[key]
            others = sorted(
                BUNDLED[other] for other in available
                if other != tag and key in counts[other] and key not in names[other]
            )
            if others:
                clashing += 1
            lines.append(f"{key}\t{cased(written, tag)}\t{','.join(others)}")
        # The pronoun on its own, as well as inside its contractions.
        for word, objectors in sorted(ALWAYS_CAPITAL.get(tag, {}).items()):
            lines.append(f"{word}\t{word[:1].upper() + word[1:]}\t{','.join(objectors)}")
        print(f"{BUNDLED[tag]}: {len(table):,} mappings, {clashing:,} of them claimed by "
              f"another bundled language")
        for key in sorted(table, key=lambda k: -table[k][1])[:arguments.sample]:
            written, count, rival = table[key]
            print(f"    {key:<12} -> {written:<14} {count:>7,} against {rival:>6,}")
        twins = pairs(
            counts[tag], names[tag], arguments.min_count,
            mine=zipf[tag], others=[zipf[o] for o in available if o != tag],
        )
        pair_lines = [
            f"{key}\t{cased(marked, tag)}\t{bare_count}\t{marked_count}"
            for key, (marked, bare_count, marked_count) in sorted(twins.items())
            if key not in table
        ]
        print(f"    pairs whose bare spelling is a word: {len(pair_lines):,}")
        if arguments.apply:
            arguments.out.mkdir(parents=True, exist_ok=True)
            path = arguments.out / f"{BUNDLED[tag]}.txt"
            path.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8")
            print(f"    written: {path}")
            pairs_path = arguments.out / f"{BUNDLED[tag]}.pairs.txt"
            pairs_path.write_text(PAIRS_HEADER + "\n".join(pair_lines) + "\n", encoding="utf-8")
            print(f"    written: {pairs_path}")
        pruned = {item.split("=", 1)[0]: (item.split("=", 1) + [""])[1]
                  for item in arguments.prune_bare}
        if tag in pruned:
            prune_bare(arguments.dictionaries / f"{tag}.tsv", table, names[tag],
                       Path(pruned[tag]) if pruned[tag] else None, arguments.apply)
        print()

    if not arguments.apply:
        print("nothing written -- pass --apply")
    return 0


def prune_bare(path: Path, table: dict, names: set[str], hunspell: Path | None,
               apply: bool) -> None:
    """Drops from the word list at [path] the rows the table rewrites, names aside, or with
    [hunspell] only those the spell checker rejects in every case form; reports them, and
    rewrites the list with --apply."""
    candidates = sorted(
        key for key, (written, _count, _rival) in table.items()
        if key not in names and written.lower() != key.lower()
    )
    counts, _ = read_list(path)
    present = [key for key in candidates if key in counts]
    if hunspell is None:
        junk = sorted(present, key=lambda k: -counts[k])
        print(f"    bare spellings in the list: {len(present)}, all dropped")
    else:
        spec = importlib.util.spec_from_file_location(
            "drop_misspellings", Path(__file__).with_name("drop_misspellings.py"))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        junk = sorted(module.rejected_in_every_case(present, hunspell), key=lambda k: -counts[k])
        print(f"    bare spellings in the list: {len(present)}, of them rejected by the spell "
              f"checker: {len(junk)}")
    for key in junk:
        print(f"        {key:<12} -> {table[key][0]:<14} {counts[key]:>7,}")
    if not apply or not junk:
        return
    dropped = set(junk)
    kept = [line for line in path.read_text(encoding="utf-8").splitlines(keepends=True)
            if line.split("\t", 1)[0] not in dropped]
    path.write_text("".join(kept), encoding="utf-8")
    print(f"    dropped {len(junk)} rows from {path}")


if __name__ == "__main__":
    raise SystemExit(main())
