#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Build an accent-restoration corpus: a word with its diacritics stripped, and the word.

Generated rather than chosen, sampling each frequency band equally.

    python3 tools/make_accent_corpus.py dictionaries/ro_RO.tsv > out.tsv
"""

import argparse
import random
import sys
import unicodedata
from pathlib import Path

# Bands by rank, not by count.
BANDS = 6
PER_BAND = 50
SEED = 20260921
MIN_LENGTH = 3


def stripped(word):
    """The word as someone types it on a layout without diacritics."""
    return "".join(
        c for c in unicodedata.normalize("NFD", word) if not unicodedata.combining(c)
    )


def read_words(path):
    words = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            try:
                words.append((parts[0], int(parts[1])))
            except ValueError:
                continue
    return words


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dictionary")
    parser.add_argument("--per-band", type=int, default=PER_BAND)
    args = parser.parse_args()

    words = read_words(args.dictionary)
    if not words:
        sys.exit(f"no words read from {args.dictionary}")
    words.sort(key=lambda pair: -pair[1])

    # Only words a diacritic-free spelling actually differs from, and only those long enough
    # that the keyboard would guess about them at all.
    accented = [
        (word, count)
        for word, count in words
        if len(word) >= MIN_LENGTH and stripped(word) != word and stripped(word).isalpha()
    ]
    if not accented:
        sys.exit("no accented words in this dictionary")

    rng = random.Random(SEED)
    size = max(1, len(accented) // BANDS)
    rows = []
    for band in range(BANDS):
        slice_ = accented[band * size : (band + 1) * size]
        if not slice_:
            continue
        rows.extend(rng.sample(slice_, min(args.per_band, len(slice_))))

    tag = Path(args.dictionary).stem.replace("_", "-")
    print(f"# {tag} words with their diacritics stripped, as someone types them on a layout")
    print("# that has none -- and the spelling the keyboard must restore. Fed to")
    print("# `suggest_eval --autocorrect`, which asks what the space bar commits.")
    print("#")
    print("# Generated by tools/make_accent_corpus.py, stratified across six frequency bands.")
    print("#")
    print(f"# {len(rows)} cases, seed {SEED}.")
    for word, _count in rows:
        print(f"{stripped(word)}\t{word}")


if __name__ == "__main__":
    main()
