#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of words with one inner letter doubled.

Each case repeats one letter that is neither the first nor the last, so reaching the intended
word needs one deletion. Emitted as `mangled<TAB>intended`, read by `suggest_eval --autocorrect`.

Cases whose mangled form is itself a dictionary word are skipped: the keyboard is right to leave
those alone.

    python3 tools/make_doubled_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import sys

SEED = 20260923
COUNT = 200
FROM_TOP = 4000
MIN_LENGTH = 5


def mangled(word, rng):
    """`word` with one inner letter doubled, never one that is already doubled."""
    positions = [at for at in range(1, len(word) - 1)
                 if word[at] != word[at - 1] and word[at] != word[at + 1]]
    if not positions:
        return None
    at = rng.choice(positions)
    return word[:at] + word[at] + word[at:]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    words = []
    known = set()
    with open(args.dictionary, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            try:
                int(parts[1])
            except ValueError:
                continue
            known.add(parts[0])
            words.append(parts[0])

    rng = random.Random(SEED)
    pool = [w for w in words[:FROM_TOP] if len(w) >= MIN_LENGTH and w.isalpha() and w.islower()]
    rows = []
    for word in pool:
        case = mangled(word, rng)
        if case is None or case in known:
            continue
        rows.append((case, word))
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    rows.sort()

    print("# Words with one inner letter doubled, so the intended word is one deletion away.")
    print("# Generated by tools/make_doubled_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {len(rows)} cases.")
    print("# Cases whose mangled form is itself a dictionary word are excluded.")
    for case, word in rows:
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
