#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of words with one inner letter left out.

Each case drops one letter that is neither the first nor the last, so reaching the intended
word needs one insertion. Emitted as `mangled<TAB>intended`, read by `suggest_eval --autocorrect`.

Cases whose mangled form is itself a dictionary word are skipped.

    python3 tools/make_omitted_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import sys

import corpus_words

SEED = 20261002
COUNT = 200
FROM_TOP = 4000
MIN_LENGTH = 5
MAX_LENGTH = 9


def mangled(word, rng):
    """`word` with one inner letter removed."""
    at = rng.randrange(1, len(word) - 1)
    return word[:at] + word[at + 1:]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    words = corpus_words.load(args.dictionary)
    rng = random.Random(SEED)
    rows = []
    for word in words.ordinary(FROM_TOP, MIN_LENGTH, MAX_LENGTH):
        case = mangled(word, rng)
        if words.is_word(case):
            continue
        rows.append((case, word))
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    rows.sort()

    print("# Words with one inner letter left out: the intended word is one insertion away.")
    print("# Generated by tools/make_omitted_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {MIN_LENGTH} to"
          f" {MAX_LENGTH} letters, {len(rows)} cases.")
    print("# Cases whose mangled form is itself a dictionary word are excluded.")
    for case, word in rows:
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
