#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of slips on frequent words that are also the start of a rare word.

Each case is a frequent word with one letter hit one key over or one inner letter left out,
where the result is not a word itself but is a proper prefix of a word ranked past RARE_FROM in
the list. The intended word is the frequent one; the rare word the typed letters begin is named
in a comment above each row. Emitted as `mangled<TAB>intended`, read by `suggest_eval
--autocorrect` and by the bare `suggest_eval`.

    python3 tools/make_rareprefix_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import bisect
import random
import sys

import corpus_words
from make_firstletter_corpus import NEAR

SEED = 20261002
COUNT = 200
FROM_TOP = 4000
RARE_FROM = 20000
MIN_LENGTH = 4
MAX_LENGTH = 9
TRIES = 6


def slipped(word, rng):
    at = rng.randrange(len(word))
    options = NEAR.get(word[at])
    if not options:
        return None
    return word[:at] + rng.choice(options) + word[at + 1:]


def omitted(word, rng):
    if len(word) < 5:
        return None
    at = rng.randrange(1, len(word) - 1)
    return word[:at] + word[at + 1:]


def rare_word_starting(rare, typed):
    """A word in the sorted list `rare` that `typed` is a proper prefix of, or None."""
    at = bisect.bisect_right(rare, typed)
    if at < len(rare) and rare[at].startswith(typed):
        return rare[at]
    return None


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    words = corpus_words.load(args.dictionary)
    rare = sorted(word for word, _name in words.rows[RARE_FROM:] if word.isalpha())
    rng = random.Random(SEED)
    rows = []
    for word in words.ordinary(FROM_TOP, MIN_LENGTH, MAX_LENGTH):
        for _ in range(TRIES):
            case = rng.choice((slipped, omitted))(word, rng)
            if case is None or case == word or words.is_word(case):
                continue
            longer = rare_word_starting(rare, case)
            if longer is not None:
                rows.append((case, word, longer))
                break
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    # One row per typed form: a form two words mangle to is kept for the first of them.
    seen = set()
    rows = [row for row in rows if not (row[0] in seen or seen.add(row[0]))]
    rows.sort()

    print("# Slips on frequent words that begin a rare word: one letter hit one key over or one")
    print("# inner letter left out, the result not a word itself but a proper prefix of a word")
    print(f"# ranked past {RARE_FROM}, named above each row. Generated by")
    print("# tools/make_rareprefix_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {MIN_LENGTH} to"
          f" {MAX_LENGTH} letters, {len(rows)} cases.")
    for case, word, longer in rows:
        print(f"# begins {longer}")
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
