#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of real words that neither the pack nor the language's spelling dictionaries
list, to check they survive typing.

The words come from Android's stock keyboard lists (LineageOS's copy, Apache-2.0), which the
list cleaning already reads: lower-case entries of make_unknown_corpus.py's lengths, all letters,
not flagged offensive or an abbreviation, whose folded key the pack lacks, and that every one of
the language's Hunspell dictionaries rejects. Sampled at random with a fixed seed. Every line is
`word<TAB>word`, the corpus idiom for "leave it alone".

    python3 tools/make_unlisted_corpus.py en_US dictionaries/en_US.tsv \\
        > native-tests/data/autocorrect_unlisted_en.tsv
"""

import argparse
import pathlib
import random
import sys

import classify_wordlist
from make_unknown_corpus import COUNT, MAX_LENGTH, MIN_LENGTH, load_fold, packed_keys

SEED = 20261004
LEFT_OUT_FLAGS = {"offensive", "abbreviation"}


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("list", choices=sorted(classify_wordlist.SOURCES))
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    parser.add_argument("--cache", type=pathlib.Path,
                        default=pathlib.Path.home() / ".cache" / "borderkeys" / "word-evidence")
    args = parser.parse_args()

    sources = classify_wordlist.SOURCES[args.list]
    fold = load_fold()
    packed = packed_keys(args.dictionary, fold)
    candidates = sorted({
        word
        for word, flags in classify_wordlist.keyboard_entries(args.cache, sources)
        if word.islower() and word.isalpha() and MIN_LENGTH <= len(word) <= MAX_LENGTH
        and flags not in LEFT_OUT_FLAGS and fold(word) not in packed
    })
    accepted = set()
    for dictionary in classify_wordlist.spelling_dictionaries(args.cache, sources):
        accepted |= classify_wordlist.hunspell_accepted(candidates, dictionary, lambda w: w)
    eligible = [word for word in candidates if word not in accepted]
    if not eligible:
        sys.exit("no stock keyboard word is missing from both the pack and the spelling dictionaries")

    rows = random.Random(SEED).sample(eligible, min(args.count, len(eligible)))
    rows.sort()
    spelling = ", ".join(path.split("/")[-1] for path in sources.spelling)
    print("# Real words from Android's stock keyboard lists (LineageOS's copy of LatinIME, Apache-2.0)")
    print(f"# that neither the bundled pack nor the {spelling} spelling dictionaries list.")
    print(f"# {len(eligible):,} are eligible; these are {len(rows)} sampled at random.")
    print("#")
    print("# Written `word<TAB>word`, the corpus idiom for \"leave it alone\".")
    print("#")
    print("# Generated by tools/make_unlisted_corpus.py, seed %d." % SEED)
    for word in rows:
        print(f"{word}\t{word}")


if __name__ == "__main__":
    main()
