#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of correct words the pack does not contain, to check they survive typing.

Being correct is not the same as being in the dictionary. A word the pack lacks gets no
known-word guard, so the pack's own words compete for it unopposed -- and this measures how
often one wins. Every line is `word<TAB>word`, the corpus idiom for "leave it alone".

Sampled at random from the whole eligible set with a fixed seed, which is the entire point of
this tool existing. The corpus it replaces took the *first* 200 words of the right length, which
is alphabetical order, so all 200 began with "a" -- and the failures it reported were dominated
by one shape ("abase" to "base", "abridge" to "bridge") that a single leading letter makes
unusually easy to reach. A measurement drawn from one corner of the alphabet cannot say how
often this happens to anyone.

Membership is tested on the folded key rather than the spelling, because that is what the pack
is keyed by: a word whose accents or case differ from a pack entry is still *in* the pack, and
counting it as absent would put words in this corpus that the known-word guard already protects.

    python3 tools/make_unknown_corpus.py <hunspell.dic> dictionaries/en_US.tsv > out.tsv
"""

import argparse
import importlib.util
import pathlib
import random
import sys

SEED = 20260921
COUNT = 200
MIN_LENGTH = 5
MAX_LENGTH = 9


def load_fold():
    """build_dict.py's own fold, so membership here means membership in the compiled pack."""
    path = pathlib.Path(__file__).with_name("build_dict.py")
    spec = importlib.util.spec_from_file_location("build_dict", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.fold_word


def headwords(path):
    """The dictionary's own entries, without their affix flags."""
    words = []
    with open(path, encoding="utf-8", errors="replace") as handle:
        for index, line in enumerate(handle):
            if index == 0 and line.strip().isdigit():
                continue  # the count Hunspell puts on line one
            word = line.strip().split("/")[0].strip()
            if word:
                words.append(word)
    return words


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("hunspell")
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    fold = load_fold()
    packed = set()
    with open(args.dictionary, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 2:
                packed.add(fold(parts[0]))

    eligible = sorted({
        word.lower()
        for word in headwords(args.hunspell)
        if MIN_LENGTH <= len(word) <= MAX_LENGTH
        and word.isalpha()
        and word.islower()
        and fold(word.lower()) not in packed
    })
    if not eligible:
        sys.exit("every eligible word is already in the pack")

    rows = random.Random(SEED).sample(eligible, min(args.count, len(eligible)))
    rows.sort()

    print("# Ordinary English words -- headwords of en_US.dic -- that the bundled pack does not")
    print(f"# contain. {len(eligible):,} are eligible; these are {len(rows)} sampled at random.")
    print("#")
    print("# Written `word<TAB>word`, the corpus idiom for \"leave it alone\". A word the pack")
    print("# lacks has no known-word guard, so the pack's own words compete for it unopposed.")
    print("#")
    print("# Generated by tools/make_unknown_corpus.py, seed %d. Sampled rather than taken in"
          % SEED)
    print("# order: the previous edition took the first 200 of the right length, so every word")
    print("# began with \"a\" and the result described one corner of the alphabet.")
    for word in rows:
        print(f"{word}\t{word}")


if __name__ == "__main__":
    main()
