#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors

"""Writes the two corpora for spellings that differ from another only by diacritics.

    python3 tools/classify_wordlist.py --tag ro_RO --review /tmp/review
    python3 tools/make_twin_corpus.py --tag ro_RO --review /tmp/review \\
        --out native-tests/data

autocorrect_twins_<code>.tsv holds the rows classify_wordlist.py dropped as twins: the spelling
without the diacritics as typed, and the spelling the keyboard must commit. autocorrect_plain_
<code>.tsv holds ordinary rows it kept beside ordinary words with more diacritics, none of them
a name, each expected to be left alone. Both sampled with a fixed seed, at most --per-file cases
each.
"""

from __future__ import annotations

import argparse
import random
import sys
import unicodedata
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_dict import fold_word  # noqa: E402

SEED = 20260929
PER_FILE = 200


def marks(word: str) -> int:
    return sum(1 for c in unicodedata.normalize("NFD", word) if unicodedata.combining(c))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag", required=True)
    parser.add_argument("--review", type=Path, required=True)
    parser.add_argument("--dictionaries", type=Path, default=Path("dictionaries"))
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--per-file", type=int, default=PER_FILE)
    arguments = parser.parse_args()

    code = arguments.tag.split("_")[0]
    rng = random.Random(SEED)

    twins = []
    dropped = arguments.review / f"{arguments.tag}.dropped.tsv"
    for line in dropped.read_text(encoding="utf-8").splitlines():
        word, kind, detail, _ = line.split("\t")
        if kind == "twin" and word == word.lower():
            twins.append((word, detail.split(";")[0].removeprefix("of ").strip()))

    rows = []
    listed = arguments.dictionaries / f"{arguments.tag}.tsv"
    for line in listed.read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if len(parts) >= 2:
            rows.append((parts[0], len(parts) > 2))
    by_key: dict[tuple[int, ...], list[str]] = {}
    for word, _ in rows:
        by_key.setdefault(fold_word(word.lower()), []).append(word)
    names = {word.lower() for word, is_name in rows if is_name}

    def ordinary_with_fuller_twin(word: str) -> bool:
        fuller = [other for other in by_key[fold_word(word)] if marks(other) > marks(word)]
        return bool(fuller) and not any(other.lower() in names for other in fuller)

    plain = [word for word, is_name in rows
             if not is_name and word == word.lower() and len(word) > 1
             and word not in names and ordinary_with_fuller_twin(word)]

    header = [
        f"# {arguments.tag}: generated by tools/make_twin_corpus.py from",
        f"# tools/classify_wordlist.py's review, seed {SEED}.",
    ]
    arguments.out.mkdir(parents=True, exist_ok=True)
    twin_sample = sorted(rng.sample(twins, min(arguments.per_file, len(twins))))
    (arguments.out / f"autocorrect_twins_{code}.tsv").write_text(
        "\n".join(header + ["# A spelling without its diacritics, and the spelling to commit."]
                  + [f"{typed}\t{expected}" for typed, expected in twin_sample]) + "\n",
        encoding="utf-8",
    )
    plain_sample = sorted(rng.sample(plain, min(arguments.per_file, len(plain))))
    (arguments.out / f"autocorrect_plain_{code}.tsv").write_text(
        "\n".join(header + ["# A word beside a spelling with more diacritics, to be left alone."]
                  + [f"{word}\t{word}" for word in plain_sample]) + "\n",
        encoding="utf-8",
    )
    print(f"{arguments.tag}: {len(twin_sample)} of {len(twins)} twins, "
          f"{len(plain_sample)} of {len(plain)} plain words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
