#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Build an accent-restoration corpus: a word with its diacritics stripped, and the word.

This is the measurement the keyboard's headline feature never had. Every corpus beside it is
English, where the question does not arise -- so the one behaviour Romanian users rely on, and
the source of nearly every report, was the one nothing measured.

The set is generated rather than chosen, and stratified by frequency on purpose. Accent
restoration does not fail uniformly: a frequent word wins on frequency whatever the rules do,
so a corpus drawn from the top of the list would report near-perfect and hide the defect
entirely. "totuși" (9,779) always worked; "cană" (170) never did. Sampling each band equally is
what makes the difference visible.

    python3 tools/make_accent_corpus.py dictionaries/ro_RO.tsv > out.tsv
"""

import argparse
import random
import sys
import unicodedata

# Bands by rank, not by count: the list is Zipfian, so equal-sized rank slices give bands whose
# frequencies differ by orders of magnitude, which is the axis being tested.
BANDS = 6
PER_BAND = 50
SEED = 20260921
MIN_LENGTH = 3


def stripped(word):
    """The word as someone types it on a layout without diacritics."""
    return "".join(
        c for c in unicodedata.normalize("NFD", word) if not unicodedata.combining(c)
    )


def read_words(path):
    words = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            try:
                words.append((parts[0], int(parts[1])))
            except ValueError:
                continue
    return words


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dictionary")
    parser.add_argument("--per-band", type=int, default=PER_BAND)
    args = parser.parse_args()

    words = read_words(args.dictionary)
    if not words:
        sys.exit(f"no words read from {args.dictionary}")
    words.sort(key=lambda pair: -pair[1])

    # Only words a diacritic-free spelling actually differs from, and only those long enough
    # that the keyboard would guess about them at all.
    accented = [
        (word, count)
        for word, count in words
        if len(word) >= MIN_LENGTH and stripped(word) != word and stripped(word).isalpha()
    ]
    if not accented:
        sys.exit("no accented words in this dictionary")

    rng = random.Random(SEED)
    size = max(1, len(accented) // BANDS)
    rows = []
    for band in range(BANDS):
        slice_ = accented[band * size : (band + 1) * size]
        if not slice_:
            continue
        rows.extend(rng.sample(slice_, min(args.per_band, len(slice_))))

    print("# Romanian words with their diacritics stripped, as someone types them on a layout")
    print("# that has none -- and the spelling the keyboard must restore. Fed to")
    print("# `suggest_eval --autocorrect`, which asks what the space bar commits.")
    print("#")
    print("# Generated by tools/make_accent_corpus.py, stratified across six frequency bands so")
    print("# the rare half is represented. That stratification is the point: restoration used to")
    print("# work for common words and fail for rare ones, so a corpus drawn from the top of the")
    print("# word list reported near-perfect while 'cana' was being committed as 'canal'.")
    print("#")
    print(f"# {len(rows)} cases, seed {SEED}.")
    for word, _count in rows:
        print(f"{stripped(word)}\t{word}")


if __name__ == "__main__":
    main()
