#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of words with one letter hit one key over, at any position.

Each case replaces one letter with a QWERTY neighbour of it, so reaching the intended word
needs one substitution between adjacent keys. Emitted as `mangled<TAB>intended`, read by
`suggest_eval --autocorrect`; with `--strip`, the same rows headed for the bare strip-rank mode.

Cases whose mangled form is itself a dictionary word are skipped.

    python3 tools/make_slip_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import sys

import corpus_words
from make_firstletter_corpus import NEAR

SEED = 20261002
COUNT = 200
FROM_TOP = 4000
MIN_LENGTH = 4
MAX_LENGTH = 9


def mangled(word, rng):
    """`word` with one letter, at a random position, replaced by one of that letter's neighbours."""
    at = rng.randrange(len(word))
    options = NEAR.get(word[at])
    if not options:
        return None
    return word[:at] + rng.choice(options) + word[at + 1:]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    parser.add_argument("--strip", action="store_true",
                        help="head the rows for the bare strip-rank mode")
    args = parser.parse_args()

    words = corpus_words.load(args.dictionary)
    rng = random.Random(SEED)
    rows = []
    for word in words.ordinary(FROM_TOP, MIN_LENGTH, MAX_LENGTH):
        case = mangled(word, rng)
        if case is None or case == word or words.is_word(case):
            continue
        rows.append((case, word))
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    rows.sort()

    print("# Words with one letter hit one key over, at any position: the intended word is one")
    print("# substitution between adjacent QWERTY keys away. Generated by")
    print("# tools/make_slip_corpus.py, seed %d." % SEED)
    print("#")
    if args.strip:
        print("# Read by the bare `suggest_eval`: where the strip ranks the intended word.")
    else:
        print("# Read by `suggest_eval --autocorrect`: what the space bar commits.")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {MIN_LENGTH} to"
          f" {MAX_LENGTH} letters, {len(rows)} cases.")
    print("# Cases whose mangled form is itself a dictionary word are excluded.")
    for case, word in rows:
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
