#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of words with one stray letter typed into them.

Each case inserts a letter at a random position, one that is neither a QWERTY neighbour of the
letters on either side of it nor a repeat of them, so reaching the intended word needs one
deletion that no cheaper reading explains. Emitted as `mangled<TAB>intended`, read by
`suggest_eval --autocorrect`.

Cases whose mangled form is itself a dictionary word are skipped.

    python3 tools/make_extra_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import string
import sys

import corpus_words
from make_firstletter_corpus import NEAR

SEED = 20261002
COUNT = 200
FROM_TOP = 4000
MIN_LENGTH = 5
MAX_LENGTH = 9


def mangled(word, rng):
    """`word` with a stray letter inserted: not a neighbour or a repeat of the letters beside it."""
    at = rng.randrange(len(word) + 1)
    beside = word[max(at - 1, 0):at] + word[at:at + 1]
    excluded = set(beside)
    for letter in beside:
        excluded.update(NEAR.get(letter, ()))
    options = [letter for letter in string.ascii_lowercase if letter not in excluded]
    if not options:
        return None
    return word[:at] + rng.choice(options) + word[at:]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    words = corpus_words.load(args.dictionary)
    rng = random.Random(SEED)
    rows = []
    for word in words.ordinary(FROM_TOP, MIN_LENGTH, MAX_LENGTH):
        case = mangled(word, rng)
        if case is None or words.is_word(case):
            continue
        rows.append((case, word))
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    rows.sort()

    print("# Words with one stray letter typed in, neither a QWERTY neighbour nor a repeat of the")
    print("# letters beside it: the intended word is one deletion away. Generated by")
    print("# tools/make_extra_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {MIN_LENGTH} to"
          f" {MAX_LENGTH} letters, {len(rows)} cases.")
    print("# Cases whose mangled form is itself a dictionary word are excluded.")
    for case, word in rows:
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
