#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of words that are both mistyped and unfinished.

Each case transposes two adjacent middle letters and drops the last character, so reaching the
intended word needs one edit and one completed character together. Emitted as
`mangled<TAB>intended`, read by `suggest_eval --autocorrect`.

Cases whose mangled form is itself a dictionary word are skipped: the keyboard is right to leave
those alone.

    python3 tools/make_midtypo_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import sys

SEED = 20260921
COUNT = 200
FROM_TOP = 4000
MIN_LENGTH = 6


def mangled(word, rng):
    """`word` with two adjacent middle letters swapped and the last character removed."""
    positions = range(1, len(word) - 2)
    if not positions:
        return None
    at = rng.choice(list(positions))
    swapped = word[:at] + word[at + 1] + word[at] + word[at + 2:]
    return swapped[:-1]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    words = []
    known = set()
    with open(args.dictionary, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            try:
                int(parts[1])
            except ValueError:
                continue
            known.add(parts[0])
            words.append(parts[0])

    rng = random.Random(SEED)
    pool = [w for w in words[:FROM_TOP] if len(w) >= MIN_LENGTH and w.isalpha() and w.islower()]
    rows = []
    for word in pool:
        case = mangled(word, rng)
        if case is None or case == word or case in known:
            continue
        rows.append((case, word))
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    rows.sort()

    print("# Words both mistyped and unfinished: two adjacent middle letters swapped and the")
    print("# last character dropped, so the intended word is one edit plus one completed")
    print("# character away. Generated by tools/make_midtypo_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {len(rows)} cases.")
    print("# Cases whose mangled form is itself a dictionary word are excluded.")
    for case, word in rows:
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
