#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 BorderKeys contributors
"""Builds a corpus of words whose first letter was hit one key over.

Each case replaces the first letter with a QWERTY neighbour of it, so reaching the intended
word needs one substitution at the position the geometry prices lowest. Emitted as
`mangled<TAB>intended`, read by `suggest_eval --autocorrect`.

Cases whose mangled form is itself a dictionary word are skipped: the keyboard is right to leave
those alone.

    python3 tools/make_firstletter_corpus.py dictionaries/en_US.tsv > out.tsv
"""

import argparse
import random
import sys

SEED = 20260923
COUNT = 200
FROM_TOP = 4000
MIN_LENGTH = 5

ROWS = ("qwertyuiop", "asdfghjkl", "zxcvbnm")


def neighbours():
    """Every letter's QWERTY neighbours: beside it on its row, and the keys above and below."""
    out = {}
    for row_index, row in enumerate(ROWS):
        for at, letter in enumerate(row):
            near = set()
            if at > 0:
                near.add(row[at - 1])
            if at + 1 < len(row):
                near.add(row[at + 1])
            for other_index in (row_index - 1, row_index + 1):
                if 0 <= other_index < len(ROWS):
                    other = ROWS[other_index]
                    for shift in (0, 1) if other_index > row_index else (-1, 0):
                        if 0 <= at + shift < len(other):
                            near.add(other[at + shift])
            out[letter] = sorted(near)
    return out


NEAR = neighbours()


def mangled(word, rng):
    """`word` with its first letter replaced by one of that letter's neighbours."""
    options = NEAR.get(word[0])
    if not options:
        return None
    return rng.choice(options) + word[1:]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dictionary")
    parser.add_argument("--count", type=int, default=COUNT)
    args = parser.parse_args()

    words = []
    known = set()
    with open(args.dictionary, encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            try:
                int(parts[1])
            except ValueError:
                continue
            known.add(parts[0])
            words.append(parts[0])

    rng = random.Random(SEED)
    pool = [w for w in words[:FROM_TOP] if len(w) >= MIN_LENGTH and w.isalpha() and w.islower()]
    rows = []
    for word in pool:
        case = mangled(word, rng)
        if case is None or case in known:
            continue
        rows.append((case, word))
    if not rows:
        sys.exit("no eligible words")

    rows = rng.sample(rows, min(args.count, len(rows)))
    rows.sort()

    print("# Words whose first letter was hit one key over on QWERTY, so the intended word is")
    print("# one substitution away at the first position. Generated by")
    print("# tools/make_firstletter_corpus.py, seed %d." % SEED)
    print("#")
    print(f"# Drawn from the {FROM_TOP} most frequent words of the pack, {len(rows)} cases.")
    print("# Cases whose mangled form is itself a dictionary word are excluded.")
    for case, word in rows:
        print(f"{case}\t{word}")


if __name__ == "__main__":
    main()
