// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 BorderKeys contributors

package com.borderkeys.i18n

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/** The catalogues themselves, checked as data, read from the shipped assets on disk. */
class CatalogueTest {

    private val directory = File("src/main/assets/translations")

    private fun catalogue(language: String): Map<String, String> =
        LanguageManager.parse(File(directory, "$language.json").readText())

    private fun languages(): List<String> =
        directory.listFiles()!!.map { it.name.removeSuffix(".json") }.sorted()

    @Test
    fun `english is complete`() {
        assertTrue("no English catalogue", catalogue(Strings.Languages.DEFAULT).isNotEmpty())
    }

    @Test
    fun `every language carries the same keys`() {
        val problems = TranslationParity.problems(languages().associateWith { catalogue(it).keys })
        assertEquals(problems.joinToString("\n"), emptyList<String>(), problems)
    }

    @Test
    fun `every shipped language has a name in every catalogue`() {
        for (language in languages()) {
            val catalogue = catalogue(language)
            for (named in languages()) {
                assertTrue("$language has no language_name_$named", "language_name_$named" in catalogue)
            }
        }
    }

    @Test
    fun `no entry doubles a percent sign`() {
        for (language in languages()) {
            for ((key, value) in catalogue(language)) {
                assertTrue("$language:$key writes %% where % is shown as itself", "%%" !in value.replace("%%s", ""))
            }
        }
    }

    @Test
    fun `no entry is blank`() {
        for (language in languages()) {
            for ((key, value) in catalogue(language)) {
                assertTrue("$language:$key is blank", value.isNotBlank())
            }
        }
    }

    @Test
    fun `placeholders match english`() {
        val english = catalogue(Strings.Languages.DEFAULT)
        val counted = TranslationParity.countedKeys(english.keys)
        for (language in languages()) {
            for ((key, value) in catalogue(language)) {
                val base = PluralRules.SUFFIXES.firstNotNullOfOrNull { suffix ->
                    key.removeSuffix(suffix).takeIf { key.endsWith(suffix) && it in counted }
                } ?: key
                if (language == Strings.Languages.DEFAULT && base == key) continue
                val expected = english[base] ?: continue
                assertEquals(
                    "$language:$key has a different number of %s than English",
                    expected.split("%s").size,
                    value.split("%s").size,
                )
            }
        }
    }

    /** Keys.kt, generated by tools/gen_keys.py, holds exactly the English keys. */
    @Test
    fun `Keys matches the english catalogue`() {
        val declared = File("src/main/java/com/borderkeys/i18n/Keys.kt")
            .readLines()
            .mapNotNull { Regex("""const val \w+ = "([^"]+)"""").find(it)?.groupValues?.get(1) }
            .toSet()
        val actual = catalogue(Strings.Languages.DEFAULT).keys
        assertEquals(
            "run tools/gen_keys.py",
            emptySet<String>(),
            (declared - actual) + (actual - declared),
        )
    }
}
